metadata:
  project_name: m_invers_5_evt_arm
  c_program_path:
  project_output:
  architecture: riscv32
  vendor: stm32
  operational_system: none
  microcontroller_unit: bluepill



target:
  board: True
  usb_port: /dev/ttyACM0
  flash_board: False




inputs:
  chosen_input: []
  types:  [int]
  bounds_min:  []
  bounds_max: []
  gen_method: none
  n_test_cases: 1



run:
  methods: evt
  deadline: 0
  function_target: main
  report: [pdf]



evt:
  number_exec: 10000
  pwcet_bounds: [1E-9, 1E-10, 1E-11, 1E-12]



ga:
  parent_selection_type: sss
  crossover_type: two_points
  mutation_type: adaptive
  mutation_percent_genes: [70,15]
  stop_criteria: True


external_libs:
  llvm_path:
  cbmc_path: