
metadata:
  project_name: bsort30_xtensa_evt
  c_program_path:
  project_output:
  architecture: riscv32
  vendor: riscv
  operational_system: none
  microcontroller_unit: esp32-c3


target:
  board: True
  usb_port: /dev/ttyACM0
  flash_board: False



inputs:
  chosen_input: [30,29,28,27,26,25,24,23,22,21,20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
  types:  [int(30)]
  bounds_min:  []
  bounds_max: []
  gen_method: none
  n_test_cases: 1


run:
  methods: evt
  deadline: 0
  function_target: main
  report: [pdf]


evt:
  number_exec: 10000
  pwcet_bounds: [1E-9, 1E-10, 1E-11, 1E-12]


ga:
  parent_selection_type: sss
  crossover_type: two_points
  mutation_type: adaptive
  mutation_percent_genes: [70,15]
  stop_criteria: True


external_libs:
  llvm_path:
  cbmc_path: